---
- name: debugging variables for task virtualbox_main	
  debug:
    var: var_task_virtualbox_main

#var_task_virtualbox_added_main: null
- name: calling task virtualbox_added
  import_tasks: virtualbox_added.yml
  when: task_state == "added"


#var_task_virtualbox_main: null
#var_task_virtualbox_main_main: null
#- name: calling task virtualbox_main
#  import_tasks: virtualbox_main.yml
#  vars:
#    var_task_virtualbox_main: "{{ var_task_virtualbox_main_main if var_task_virtualbox_main_main is defined else '_NOT_ASSIGNED_' }}"
#  when: var_task_virtualbox_main_action == "main"

#- name: calling task virtualbox_main directly
#  import_role:
#    name: virtualbox
#    tasks_from: virtualbox_main.yml
#  when: var_task_virtualbox_main_action == "virtualbox_main"

#var_task_virtualbox_added: null
#var_task_virtualbox_added_main: null
#- name: calling task virtualbox_added
#  import_tasks: virtualbox_added.yml
#  vars:
#    var_task_virtualbox_added: "{{ var_task_virtualbox_added_main if var_task_virtualbox_added_main is defined else '_NOT_ASSIGNED_' }}"
#  when: var_task_virtualbox_main_action == "added"

#- name: calling task virtualbox_added directly
#  import_role:
#    name: virtualbox
#    tasks_from: virtualbox_added.yml
#  when: var_task_virtualbox_main_action == "virtualbox_added"

#var_task_virtualbox_read: null
#var_task_virtualbox_read_main: null
#- name: calling task virtualbox_read
#  import_tasks: virtualbox_read.yml
#  vars:
#    var_task_virtualbox_read: "{{ var_task_virtualbox_read_main if var_task_virtualbox_read_main is defined else '_NOT_ASSIGNED_' }}"
#  when: var_task_virtualbox_main_action == "read"

#- name: calling task virtualbox_read directly
#  import_role:
#    name: virtualbox
#    tasks_from: virtualbox_read.yml
#  when: var_task_virtualbox_main_action == "virtualbox_read"

#var_task_virtualbox_updated: null
#var_task_virtualbox_updated_main: null
#- name: calling task virtualbox_updated
#  import_tasks: virtualbox_updated.yml
#  vars:
#    var_task_virtualbox_updated: "{{ var_task_virtualbox_updated_main if var_task_virtualbox_updated_main is defined else '_NOT_ASSIGNED_' }}"
#  when: var_task_virtualbox_main_action == "updated"

#- name: calling task virtualbox_updated directly
#  import_role:
#    name: virtualbox
#    tasks_from: virtualbox_updated.yml
#  when: var_task_virtualbox_main_action == "virtualbox_updated"

#var_task_virtualbox_deleted: null
#var_task_virtualbox_deleted_main: null
#- name: calling task virtualbox_deleted
#  import_tasks: virtualbox_deleted.yml
#  vars:
#    var_task_virtualbox_deleted: "{{ var_task_virtualbox_deleted_main if var_task_virtualbox_deleted_main is defined else '_NOT_ASSIGNED_' }}"
#  when: var_task_virtualbox_main_action == "deleted"

#- name: calling task virtualbox_deleted directly
#  import_role:
#    name: virtualbox
#    tasks_from: virtualbox_deleted.yml
#  when: var_task_virtualbox_main_action == "virtualbox_deleted"

