---
# defaults file for user

# default password: vagrant
#user_default_password: $6$52Q7u45jXt$km6ktHMvas2ZRekf06J9CBtHEIR.J8ExICM1Lx1gqoSgzwD9ZWceXIlZAEJIM85dagtt4DQXGUJ3KmBn78jWr1
# default password: Super123
user_default_password: $6$7l/tr/ZFrF0NyyfM$NGSn2er.NnOl0PTCdyFFfFRLj2Wf2dziS1cMNdR8iEn6x3NGpxtORuYJSuhx6vgBBx0qXAOCA2WlDsuKblVNv0

#user_task_action: create

# for creating groups (if empty, groups will not be created)
user_groups: []
#user_groups:
#  - lab2
#  - lab3

user_users:
  - name: none
  - nopasswd: no
  - groups: []
  - ssh_key: no
#user_users:
#  - name: vagrant
#    #password: "{{user_default_password}}"
#    nopasswd: yes
#    groups: "{{user_groups_admin}}"
#    ssh_key: yes
#  - name: vagrant2
#    #password: "{{user_default_password}}"
#    nopasswd: no
#    groups: "{{user_groups_guest}}"
#    ssh_key: yes
