---
- hosts:
    - localhost
    #- otherhost
  roles:
    - {role: test, action: create}
    #- {role: test, action: read}
    #- {role: test, action: update}
    #- {role: test, action: delete}
    #- {role: test, action: test_create}
    - {role: test, action: test_read}
    #- {role: test, action: test_update}
    #- {role: test, action: test_delete}
  vars_files:
    - ./test_vars_main_template.yml
    - ./test_vars_create_template.yml
    - ./test_vars_read_template.yml
    - ./test_vars_update_template.yml
    - ./test_vars_delete_template.yml
  #vars:
### test_main_variables
#test_main_var: "value from playbook vars - main"
#test_main_var_as_action_create: "value from playbook vars - main"
#test_main_var_as_action_read: "value from playbook vars - main"
#test_main_var_as_action_update: "value from playbook vars - main"
#test_main_var_as_action_delete: "value from playbook vars - main"
#test_main_var_as_action_test_create: "value from playbook vars - main"
#test_main_var_as_action_test_read: "value from playbook vars - main"
#test_main_var_as_action_test_update: "value from playbook vars - main"
#test_main_var_as_action_test_delete: "value from playbook vars - main"
### test_create_variables
#test_create_var: "value from playbook vars - create"
### test_read_variables
#test_read_var: "value from playbook vars - read"
### test_update_variables
#test_update_var: "value from playbook vars - update"
### test_delete_variables
#test_delete_var: "value from playbook vars - delete"
