---

- name: entering ex01 main 
  debug:
    var: v1
- name: import role ex02
  import_role: 
    name: ex02
    tasks_from: task1.yml
  vars:
    ex02_v1: none
  #vars:
    #v1: "ex02_task1"
- name: debugging v2
  debug:
    var: v2
- name: debugging v3
  debug:
    var: v3
