---
# tasks file for user

- name: adding user
  user:
    name: "{{ item.name }}"
    #groups: sudo
    #password: "{{ item.password }}"
    password: "{{ user_default_password }}"
    append: yes
    generate_ssh_key: "{{ item.ssh_key }}"
  become: yes
  with_items:
    "{{ user_users }}"

- name: setting sudo no password to the user
  lineinfile:
    path: /etc/sudoers
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    state: present
  when: item.nopasswd == true
  become: yes
  with_items:
    "{{ user_users }}"

- name: adding groups
  import_role: 
    name: group
  vars:
    group_groups: "{{ user_groups }}"
    group_task_action: group_add
  when: user_groups is defined

- name: adding users to the designated group(s)
  user:
    #name: "{{ ansible_user_id }}"
    name: "{{ item.0.name }}"
    groups: "{{ item.1 }}"
    append: yes
  become: yes
  #notify: resetting ssh connection
  with_subelements:
    - "{{ user_users }}"
    - groups

# reset ssh connection to allow user changes to affect 'current login user'
#- name: resetting ssh connection
#  meta: reset_connection

#- name: testing libvirt output
#  command: virsh list --all
#  register: virsh_list
#- debug:
#   var: virsh_list.stdout_lines
