---

#- hosts: physical
- hosts: 
    - phy02
    - phy03
  roles:
    - { role: group, group_task_action: group_add }
    - { role: user, user_task_action: user_add }
    - { role: kvm, kvm_task_action: kvm_add }
    - { role: nw }
    - { role: ipmitool, ipmitool_task_action: ipmitool_add }
    - { role: sshd, sshd_task_action: sshd_config_update }
    
  vars_files:
    - test_vars.yml
    #- nw_if_vagrant_client.yml
    - nw_if_baremetal_compute.yml

- hosts: 
    - phy01
  roles:
    - { role: group, group_task_action: group_add }
    - { role: user, user_task_action: user_add }
    #- { role: kvm, kvm_task_action: kvm_add }
    - { role: nw }
    - { role: ipmitool, ipmitool_task_action: ipmitool_add }
    - { role: sshd, sshd_task_action: sshd_config_update }
    - { role: maas, maas_task_action: maas_add }
  vars_files:
    - test_vars.yml
    #- nw_if_vagrant_client.yml
    - nw_if_baremetal_compute.yml

- hosts: none
  roles:
    - { role: group, group_task_action: group_add }
    - { role: user, user_task_action: user_add }
    - { role: kvm, kvm_task_action: kvm_add }
    - { role: nw }
  vars_files:
    - test_vars.yml
    #- nw_if_vagrant_client.yml
    - nw_if_baremetal_compute.yml

#- hosts: phy02
#  roles:
#    - { role: maas, maas_action: maas_add }
#  vars_files:
#    - test_vars.yml
